export const GET_SEARCH_ID = "GET_SEARCH_ID";
export const GET_TICKETS_LIST = "GET_TICKETS_LIST";

export const SET_TRANSFER_FILTER = "SET_TRANSFER_FILTER";

export const SHOW_ALL_TICKETS = "SHOW_ALL_TICKETS";
export const SHOW_CHEAPEST_TICKETS = "SHOW_CHEAPEST_TICKETS";
export const SHOW_FASTEST_TICKETS = "SHOW_FASTEST_TICKETS";
export const SHOW_OPTIMAL_TICKETS = "SHOW_OPTIMAL_TICKETS";

export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";

export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";
