export const GET_TICKETS_LIST = "GET_TICKETS_LIST";
export const SHOW_ALL_TICKETS = "SHOW_ALL_TICKETS";
export const SET_TRANSFER_FILTER = "SET_TRANSFER_FILTER";
export const SET_TAB_FILTER = "SET_TAB_FILTER";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";
